<a href="https://colab.research.google.com/github/siyabagaria/time-series-forecasting/blob/main/notebooks/analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files
uploaded = files.upload()

Saving baselines.csv to baselines.csv

In [4]:
import pandas as pd

df = pd.read_csv("baselines.csv")
df.head()

  dataset          model  horizon  seed       MAE      RMSE      time  params
0     uci  SeasonalNaive       24     0  0.565882  0.839050  0.000000       0
1     uci         Linear       24     0  0.493603  0.660613  0.027153    2328
2     uci  SeasonalNaive       24     1  0.565882  0.839050  0.000000       0
3     uci         Linear       24     1  0.493603  0.660613  0.027153    2328
4     uci  SeasonalNaive       24     2  0.565882  0.839050  0.000000       0

In [5]:
table = df.groupby(["dataset", "model", "horizon"])["MAE"].agg(["mean", "std"])
table

                                   mean  std
dataset model         horizon
ecl     Linear        24       0.478590  0.0
                      96       0.491796  0.0
        SeasonalNaive 24       0.489220  0.0
                      96       0.594129  0.0
ett     Linear        24       0.154395  0.0
                      96       0.243758  0.0
        SeasonalNaive 24       0.205536  0.0
                      96       0.289802  0.0
uci     Linear        24       0.493603  0.0
                      96       0.512646  0.0
        SeasonalNaive 24       0.565882  0.0
                      96       0.603521  0.0

In [6]:
table = df.groupby(["dataset", "model", "horizon"])["RMSE"].agg(["mean", "std"])
table

                                   mean  std
dataset model         horizon
ecl     Linear        24       0.728303  0.0
                      96       0.748444  0.0
        SeasonalNaive 24       0.879961  0.0
                      96       1.021119  0.0
ett     Linear        24       0.211543  0.0
                      96       0.320254  0.0
        SeasonalNaive 24       0.268371  0.0
                      96       0.377997  0.0
uci     Linear        24       0.660613  0.0
                      96       0.677325  0.0
        SeasonalNaive 24       0.839050  0.0
                      96       0.874676  0.0

In [8]:
table = df.groupby(["dataset", "model", "horizon"])[["MAE", "RMSE"]].agg(["mean", "std"]).round(4)

table

                                  MAE         RMSE
                                 mean  std    mean  std
dataset model         horizon
ecl     Linear        24       0.4786  0.0  0.7283  0.0
                      96       0.4918  0.0  0.7484  0.0
        SeasonalNaive 24       0.4892  0.0  0.8800  0.0
                      96       0.5941  0.0  1.0211  0.0
ett     Linear        24       0.1544  0.0  0.2115  0.0
                      96       0.2438  0.0  0.3203  0.0
        SeasonalNaive 24       0.2055  0.0  0.2684  0.0
                      96       0.2898  0.0  0.3780  0.0
uci     Linear        24       0.4936  0.0  0.6606  0.0
                      96       0.5126  0.0  0.6773  0.0
        SeasonalNaive 24       0.5659  0.0  0.8390  0.0
                      96       0.6035  0.0  0.8747  0.0

In [9]:
table.to_csv("mae_rmse_table.csv")